# .scrutinizer.yml

build:

  dependencies:
    before:
      - rm composer.lock

  # ests:
  #  override:
  #    -
  #      # The 'phpdbg -qrr' will make Scrutinizer generating coverage with PHP 8
  #      command: 'composer phpunit-coverage'
  #      coverage:
  #        file: 'tests/build/clover.xml'
  #        format: 'clover'

  nodes:

    php73:
      environment:
        php: 7.3

    php74:
      environment:
        php: 7.4

    php80:
      environment:
          php: 8.0


checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*
